import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import {
  AnimalsByTypeQueryResult,
  useAnimalsByTypeQuery,
  useAnimalsQuery,
} from "../types/cms";

const Home: NextPage<{ animalsQueryResult: AnimalsByTypeQueryResult }> = ({}) => {
  const [currentAnimalType, setCurrentAnimalType] = useState<string | null>();

  const { data, loading } = useAnimalsByTypeQuery();

  if (loading || !data) {
    return <div>Loading...</div>;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div>
          <h2>Animal Types</h2>
          {data.animalTypes?.data.map(({ attributes }) => {
            return (
              <button
                onClick={() => setCurrentAnimalType(attributes?.name)}
                key={attributes?.name}
              >
                {attributes?.name}
              </button>
            );
          })}
        </div>

        {currentAnimalType && (
          <div>
            {data.animalTypes?.data
              .find((animalType) => animalType.attributes?.name === currentAnimalType)
              ?.attributes?.animals?.data.map((animal) => {
                return (
                  <Link key={animal.attributes?.name} href={`/animals/${animal.id}`}>
                    <button>{animal.attributes?.name}</button>
                  </Link>
                );
              })}
          </div>
        )}
      </main>
    </div>
  );
};

// export async function getServerSideProps() {
//   // const { data } = await apolloClient.query<
//   //   QueryResult<AnimalsByTypeQuery, AnimalsByTypeQueryVariables>,
//   //   {}
//   // >({
//   //   query: AnimalsByTypeDocument,
//   // });

//   const {} = useAnimalsByTypeQuery();

//   console.log(data.animalTypes);

//   // Pass data to the page via props
//   return { props: { animalsQueryResult } };
// }

export default Home;
